name: 'flight_delay_analytics'
version: '1.0.0'
config-version: 2

# This setting points to the profile defined in profiles.yml
profile: 'flight_delay_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_active_folder"
  - "dbt_packages"

# Configure models
models:
  flight_delay_analytics:
    # Applies to all models under models/staging/
    staging:
      +materialized: view
    # Applies to all models under models/marts/
    marts:
      +materialized: table
